# Quick Pipeline Test Configuration FOR VM
# Purpose: Validate pipeline runs without errors (5-10 minutes)
# Usage: python3 train_new.py training_args_quick_test_vm.yaml

model:
  n_input_features: 512
  n_units: 768
  rnn_dropout: 0.4
  rnn_trainable: true
  n_layers: 5
  patch_size: 14
  patch_stride: 4
  audio_embedding_dim: 1280

  input_network:
    n_input_layers: 1
    input_layer_sizes:
    - 512
    input_trainable: true
    input_layer_dropout: 0.2

  t2a_model_id: "facebook/mms-tts-eng"
  a2t_model_id: "Qwen/Qwen2-Audio-7B-Instruct"

# QUICK TEST PARAMETERS
gpu_number: '0'
mode: train
use_amp: true

output_dir: trained_models/quick_test
checkpoint_dir: trained_models/quick_test/checkpoint
init_from_checkpoint: false
save_best_checkpoint: true
save_all_val_steps: false
save_final_model: true
early_stopping: false  # Don't stop early in test

# MINIMAL TRAINING
num_training_batches: 10  # Just 10 batches!
lr_scheduler_type: cosine

lr_max: 0.005
lr_min: 0.0001
lr_decay_steps: 10
lr_warmup_steps: 2
lr_max_day: 0.005
lr_min_day: 0.0001
lr_decay_steps_day: 10
lr_warmup_steps_day: 2

beta0: 0.9
beta1: 0.999
epsilon: 0.00000001
weight_decay: 0.001
weight_decay_day: 0
seed: 10
grad_norm_clip_value: 10

alpha: 1.0
beta: 1.0

# FREQUENT LOGGING
batches_per_train_log: 1  # Log every batch
batches_per_val_step: 5   # Validate after 5 batches
log_individual_day_val_metrics: true
save_val_logits: false
save_val_data: false

dataset:
  data_transforms:
    white_noise_std: 1.0
    constant_offset_std: 0.2
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 3
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2

  neural_dim: 512
  batch_size: 4  # Small batch
  days_per_batch: 1  # Single day
  seed: 1
  num_dataloader_workers: 0
  loader_shuffle: false

  dataset_dir: /home/Siddharth/data/hdf5_data_final
  bad_trials_dict: null

  # SINGLE SESSION for quick test
  sessions:
  - t15.2023.08.11

  dataset_probability_val:
  - 1
