# Overfitting Test Configuration
# Purpose: Verify model can learn by overfitting small dataset (30-60 min)
# Expected: Training loss should drop significantly (e.g., 5.0 -> 0.5)

model:
  n_input_features: 512
  n_units: 768
  rnn_dropout: 0.0  # DISABLE dropout for overfitting
  rnn_trainable: true
  n_layers: 5
  patch_size: 14
  patch_stride: 4
  audio_embedding_dim: 1280

  input_network:
    n_input_layers: 1
    input_layer_sizes:
    - 512
    input_trainable: true
    input_layer_dropout: 0.0  # DISABLE dropout

  t2a_model_id: "facebook/musicgen-melody"
  a2t_model_id: "openai/whisper-base"

gpu_number: '0'
mode: train
use_amp: true

output_dir: trained_models/overfit_test
checkpoint_dir: trained_models/overfit_test/checkpoint
init_from_checkpoint: false
save_best_checkpoint: true
save_all_val_steps: false
save_final_model: true
early_stopping: false  # Let it overfit fully

# OVERFITTING PARAMETERS
num_training_batches: 2000  # 30-60 minutes
lr_scheduler_type: cosine

# HIGHER learning rate for faster overfitting
lr_max: 0.01  # 2x normal
lr_min: 0.0001
lr_decay_steps: 2000
lr_warmup_steps: 100
lr_max_day: 0.01
lr_min_day: 0.0001
lr_decay_steps_day: 2000
lr_warmup_steps_day: 100

beta0: 0.9
beta1: 0.999
epsilon: 0.00000001
weight_decay: 0.0  # DISABLE weight decay for overfitting
weight_decay_day: 0
seed: 42  # Fixed seed
grad_norm_clip_value: 10

alpha: 1.0
beta: 1.0

batches_per_train_log: 50
batches_per_val_step: 200
log_individual_day_val_metrics: true
save_val_logits: false
save_val_data: false

dataset:
  data_transforms:
    white_noise_std: 0.0  # DISABLE augmentation
    constant_offset_std: 0.0
    random_walk_std: 0.0
    random_walk_axis: -1
    static_gain_std: 0.0
    random_cut: 0  # DISABLE random cut
    smooth_kernel_size: 100
    smooth_data: true
    smooth_kernel_std: 2

  neural_dim: 512
  batch_size: 16  # Medium batch
  days_per_batch: 1
  seed: 42  # Fixed seed - same data every epoch
  num_dataloader_workers: 0
  loader_shuffle: false  # Consistent batches

  dataset_dir: /home/Siddharth/data/hdf5_data_final
  bad_trials_dict: null

  # SINGLE SESSION
  sessions:
  - t15.2023.08.11

  dataset_probability_val:
  - 1
